# Generated by Django 5.2.6 on 2025-09-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_filmcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(to='api.actor'),
        ),
        migrations.DeleteModel(
            name='FilmCredit',
        ),
    ]
