apiVersion: batch/v1
kind: Job
metadata:
  name: filmdatahub-migration
  labels:
    app: filmdatahub-migration
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: filmdatahub-migration
          image: filmdatahubregistry.azurecr.io/filmdatahub:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "python manage.py migrate"]
          env:
          - name: DATABASE_NAME
            value: filmdatahub-db
          - name: DATABASE_USERNAME
            value: user123
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: filmdatahub-secret
                key: DATABASE_PASSWORD
          - name: DATABASE_HOST
            value: filmdatahub-dbserver.mysql.database.azure.com
          - name: DATABASE_PORT
            value: "3306"