name: Build and Test Docker Image

on:
  pull_request:
  workflow_dispatch:

jobs:
  planAzureInfrastructure:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.13.1

      # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

  planAWSInfrastructure:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4
      
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [planAzureInfrastructure, planAWSInfrastructure]
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Builds and pushes an image up to your Azure Container Registry
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: mysite
          push: false
