name: Build and Test Docker Image

on:
  pull_request:
  workflow_dispatch:

jobs:
  planAzureInfrastructure:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.13.1

      # Initialize Terraform
      - name: Initialize Terraform
        working-directory: ./azure
        run: terraform init

      # Validate Terraform Code
      - name: Validate Terraform
        working-directory: ./azure
        run: terraform validate

      # Generate Terraform Plan
      - name: Terraform Plan
        working-directory: ./azure
        run: terraform plan -no-color

  planAWSInfrastructure:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4
      
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [planAzureInfrastructure, planAWSInfrastructure]
    steps:
      # Checks out the repository and set everything up
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      # Builds and pushes an image up to your Azure Container Registry
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
          -t filmdatahub:latest --load .
